### ISSUE TITLE
Create a Slack for coordination

### ISSUE THREAD

**Issue by helje5** [JorgePe/BOOSTreveng#11]
A Slack would be nice to talk about stuff? I made a LegoBoost one, want to use this? Just let me know so I can add people.

**Comment by hobbyquaker** [comment]
👍

**Comment by helje5** [comment]
Invite link: https://join.slack.com/t/legoboost/shared_invite/MjMxNzYxMTIwNzM3LTE1MDM4MjU4NTEtNGQwNWQwNDk5NQ

**Comment by undera** [comment]
THis link probably needs to be placed on README, and this bug to be closed.

**Comment by undera** [comment]
Also, there can be a gitter room, quite convenient for anyone who's on GitHub

**Comment by JorgePe** [comment]
Added link to README.
Closing at request.
