### ISSUE TITLE
6-axis tilt sensor

### ISSUE THREAD

**Issue by JorgePe** [JorgePe/BOOSTreveng#14]
I have a doubt: is it possible to read yaw with the App?
I mean, with the Move Hub always horizontal, measure when it rotates left or right? 

I can read roll and pitch but not yaw. Both with the App and directly through gatttool.
I was expecting that a 6-axis tilt sensor would get all 3 types of movement.

**Comment by hobbyquaker** [comment]
can confirm that, only pitch and roll and only -90 to 90 degrees.

**Comment by JorgePe** [comment]
Danielle Benedettelli thinks there is a chance that only 2 values are read each time but there's hope for a future firmware that allows choosing which 2 values to read.
So let's hope.
