### ISSUE TITLE
another way to program it directly with iPad or iPhone

### ISSUE THREAD

**Issue by mithrendal** [JorgePe/BOOSTreveng#15]
Hi @JorgePe ,

nice that you did this work !

I just wanted to let you know that I found another way of programming it directly from an iPad or iPhone in python.

Just in case you don't have your mac, notebook or raspberry pi with you. ;-)
 
https://github.com/mithrendal/boostanista

best regards

**Comment by JorgePe** [comment]
Hi.
Thanks. Will add you link
