### ISSUE TITLE
identify LEGO App blocks

### ISSUE THREAD

**Issue by JorgePe** [JorgePe/BOOSTreveng#20]
There are lots of blocks in the App. I understand the purpose of most but there a few I am not sure (having a small phone instead of a  tablet doesn't help).

Even when knowing the purpose of a block, I don't know the proper way to refer it unless call it "the 13th orange block from the left".

I have put a few screenshots in [this folder] (https://github.com/JorgePe/BOOSTreveng/tree/master/LEGO_BOOST_App_blocks) and I was thinking on creating some kind of page with an explanation of all blocks.

**Comment by Fransie1** [comment]
You can contact Lego Customer Service and ask for a "Block cheat sheet". They're working on making it available on their support website, and they were kind enough to send me an early version (0.03). They did ask me not to share the pdf, unfortunately. I don't know if they are willing to share more technical data. They did hint that there was more Boost to come.

The blocks you uploaded are:
ColorSensor_continuous.png = REPORT CURRENT COLOR SEEN BY SENSOR
ColorSensor_light.png = REPORT CURRENT AMBIENT LIGHT LEVEL
DistanceSensor_continuous.png= REPORT CURRENT DISTANCE FROM SENSOR
ExtMotorRotation.png = REPORT CURRENT EXTERNAL MOTOR POSITION
RGB_LED_color.png = SET HUB LIGHT TO COLOR

Frans

**Comment by JorgePe** [comment]
Thanks!

**Comment by JorgePe** [comment]
Thanks for the tip. Got v0.04. Now I undestand some commands ike "reset encoders".
