### ISSUE TITLE
Unable to make the app inventor example work

### ISSUE THREAD

**Issue by NicolasMassart** [JorgePe/BOOSTreveng#25]
Hi, I always have the following error :

>  Runtime error : Failed resolution of : Lcom/google/common/collect/Lists;

using the list in the WriteBytesWithResponse block.
I read [it was a known error and Evan Patton seems to work on it](https://groups.google.com/forum/#!msg/mitappinventortest/AgAOhYKOvko/tIWQZXZXBwAJ) but as you seems to have succeeded I guess you found a way to make it work with the current version.
Could you indicate how ?
Thanks for your nice work.

**Comment by JorgePe** [comment]
Hi. On my case it was just a matter of changing my Android phone default storage settings from SD Card to Internal Storage, not sure if I had to reinstall MIT App Inventor 2 again or not.
After making that change, I manage to run my programs through the App companion (USB tethered) and also my generated APK files.

**Comment by NicolasMassart** [comment]
I don't seem to have this parameter on mine... What Android version are you using ?

**Comment by JorgePe** [comment]
Android 5.0
Settings > Storage > Default location: SD Card / Internal Storage

**Comment by NicolasMassart** [comment]
@JorgePe It seems to be different on Android 6. There's no more default location.
I guess I'll have to wait for the fix in the BLE extension.
Thanks.
