### ISSUE TITLE
Train motor AutoID/resistor?

### ISSUE THREAD

**Issue by nathankellenicki** [JorgePe/BOOSTreveng#31]
Hi Jorge,

Do you happen to know/are you able to measure the resistance for the AutoID on the train motor?

I ask as using a 2k2 resistor should mimic a WeDo motor, but when used with a Powered UP controller, this will result in "bang-bang" style on/off operation. If we can mimic a train motor instead, then it will allow continuous variable power to be provided when using a PUP controller.

Cheers,
Nathan

**Comment by JorgePe** [comment]
Yes:
3 to 6 and 4 to 5 (no resistors, just shunts)

**Comment by nathankellenicki** [comment]
Aha thank you!

Do sensors and the Boost motor adhere to the same resistance based system, or do they have a more advanced handshake?

**Comment by nathankellenicki** [comment]
I see, I figured it was slightly more complex for those types of devices. I don't have much hardware experience so I'll have to make myself happy with the simple AutoID's of the wedo/train motors. :) Mimicking a train motor will suffice for the conversion cable I plan on making (since Lego has disappointingly said they won't be making one...)

Thanks!
