### ISSUE TITLE
Any possibility for LEGO App-Controlled Batmobile 76112?

### ISSUE THREAD

**Issue by liangqi** [JorgePe/BOOSTreveng#36]
Haven't bought yet, just query. Thanks for your work.

**Comment by JorgePe** [comment]
Hi.
I've paused development on this (personal reasons, sorry).
It is possible with some minor arrangements but there are already much better projects, see
@undera library:
https://github.com/undera/pylgbst

**Comment by liangqi** [comment]
@JorgePe thanks for your reply and effort in this project.
