### ISSUE TITLE
First byte in commands

### ISSUE THREAD

**Issue by rblaakmeer** [JorgePe/BOOSTreveng#5]
To further help (a little) in reverse engineering the protocol: Looking at all the example commands, the first byte must be the total number of bytes in the command:
- 0c:00:81:37:11:09:64:00:32:64:7f:03 is 12 bytes (0x0C)
- 0d:01:81:39:11:0a:64:00:32:32:64:7f:03 is 13 bytes (0x0D)
- 08:00:81:32:11:51:00:01 is 8 bytes (0x08)
and from the BoostRemote example app: 
- 09:00:81:(port):11:07:(power):64:03 is 9 bytes (0x09)

**Comment by JorgePe** [comment]
Nice finding! Thanks!

**Comment by JorgePe** [comment]
The responses from BOOST Move Hub also start with the length of the message - activating notifications and sending command to read color from Color Sensor, the Move Hub starts a new message each time the color changes:

```
gatttool -b 00:16:53:A4:CD:7E --char-write-req --handle=0x0f --value=0100
gatttool -b 00:16:53:A4:CD:7E --char-write-req --handle=0x0e --value=0a004101080100000001 --listen
Notification handle = 0x000e value: 08 00 45 01 ff 09 ff 01 
Notification handle = 0x000e value: 08 00 45 01 ff 08 ff 01 
Notification handle = 0x000e value: 08 00 45 01 ff 09 ff 01 
Notification handle = 0x000e value: 08 00 45 01 ff 08 ff 01 
Notification handle = 0x000e value: 08 00 45 01 ff 09 ff 01 
Notification handle = 0x000e value: 08 00 45 01 ff 08 ff 01
...
```

I'm updating my files with this information.
I'm also giving credit to your github account name. If you like any other way please say so.

Thanks again!
