### ISSUE TITLE
Nodejs API

### ISSUE THREAD

**Issue by hobbyquaker** [JorgePe/BOOSTreveng#7]
Hi Jorge,

first of all: many thanks for publishing your findings!

I wanted to leave a note here that I started to implement a Node.js module based on your work:
https://github.com/hobbyquaker/node-movehub - contributions welcome :-)

Regards,
Sebastian

**Comment by JorgePe** [comment]
Hello Sebastian.
I'm always delighted when someone finds some use to my crazyness :)
I'm almost finishing my holidays in a place with horrible communications but I promise I'll take a better look to your Node.js module. I have no experience with Node.js except for when I used node-red for a fast MQTT demo with MINDSTORMS EV3.
I'll add a link to your project, the more languages or environments available for BOOST the better.

**Comment by hobbyquaker** [comment]
Nice 👍  a "boost2mqtt" interface and a "node-red-contrib-boost" is also something I was thinking about to make as soon as the Node module is done. I'm a big fan of MQTT, my whole house is full of mqtt connected "things" and I published a bunch of MQTT interfaces on github also...  :)
